config/routes.rb
Rails.application.routes.draw do
  root "homes#homepage"
  get "nft_collection",to: "homes#nft_collection"
  get "create_nft",to: "homes#create_nft"
  get "edit_nft", to: "homes#edit_nft"
  get "nft_detail", to: "homes#nft_detail"
  get "profile",to: "homes#profile"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def homepage
    end

    def nft_collection
    end

    def create_nft
    end

    def profile
    end

    def edit_nft
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/_form.html.erb
<%= form_tag do %>
    <div class="text-[12px] text-gray-400">*Required Fields</div>
    <div class="text-[20px] text-gray-800 mt-2 font-bold">Image, Video, Audio, or 3D Model *</div>
    <div class="text-[12px] text-gray-400 mt-2">File types supported: JPG, PNG, GIF, SVG, MP4, WEBM, MP3, WAV, OGG, GLB, GLTF. Max size: 100 MB</div>

    <label class="mt-2 flex flex-col w-full h-fit border-4 border-gray-200 border-dashed hover:bg-gray-100 hover:border-gray-300">
        <div class="flex flex-col justify-center">
            <div class="justify-center">
            <img id="item-image" class="w-[56%] h-full">
            </div>
            <!-- <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-gray-400 group-hover:text-gray-600"
                fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
            </svg>
            <p class="pt-1 text-sm tracking-wider text-gray-400 group-hover:text-gray-600">
                Attach a file
            </p> -->
        </div>
        <%= file_field_tag :upload_file ,id:"item-image-field" ,class: "opacity-0" %>                
    </label>
    <%= label_tag :name, "Name", class:"mt-8 text-[20px] font-bold block text-sm text-gray-700"  %>
        <%= text_field_tag :name,"",id: "name",placeholder: "Item Name", class:" mt-4 appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-sky-500 focus:border-sky-500 sm:text-sm" %>
    </div>
    <div class="space-y-1">
        <%= label_tag :description,"Description",  class:"mt-8 text-[20px] font-bold block text-sm text-gray-700"  %>
        <%= text_field_tag :description,"",id: "description", placeholder: "Provide a detailed description of your item.", class:"mt-4 appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-sky-500 focus:border-sky-500 sm:text-sm" %>
    </div>
    <div class="space-y-1">
        <%= label_tag :external_link,"External Link",  class:"mt-4 text-[20px] font-bold block text-sm text-gray-700"  %>
        <%= text_field_tag :external_link,"",id: "external-link", placeholder: "External Link", class:"mt-4 appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-sky-500 focus:border-sky-500 sm:text-sm" %>
    </div>
    <div class="space-y-1 mt-2">
        <% if params[:edit] == "true" %>
            <input type="hidden" id="token-id">
            <button type="button" id="update-nft" class="w-full mt-8 flex justify-center py-4 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
                Update
            </button>
        <% else %>
            <button type="button" id="create-nft" class="w-full mt-8 flex justify-center py-4 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
                Create
            </button>
        <% end %>
    </div>     
<% end %>   

app/views/homes/_header.html.erb
<div class="bg-[#04111d] w-screen px-[1.2rem] py-[0.8rem] flex">
      <a href="/">
        <div class="flex items-center cursor-pointer">
          <img src=<%= image_url("opensea.png")%> height=40 width=40 />
          <div class="ml-[0.8rem] text-white font-semibold text-2xl">CsSoft</div>
        </div>
      </a>
      <div class="flex flex-1 mx-[0.8rem] w-max-[520px] items-center bg-[#363840] rounded-[0.8rem] hover:bg-[#4c505c]">
        <div class="text-[#8a939b] mx-3 font-bold text-lg">
          
        </div>
        <input class="h-[2.6rem] w-full border-0 bg-transparent outline-0 ring-0 px-2 pl-0 text-[#e6e8eb] placeholder:text-[#8a939b]"
          placeholder="Search items, collections, and accounts"
        />
      </div>
      <div class="flex items-center justify-end">
        <%= link_to nft_collection_path do %>
          <div class="text-white px-4 font-bold text-[#c8cacd] hover:text-white cursor-pointer"> Collections </div>
        <% end %>
        <div class="text-white px-4 font-bold text-[#c8cacd] hover:text-white cursor-pointer"> Stats </div>
        <div class="text-white px-4 font-bold text-[#c8cacd] hover:text-white cursor-pointer"> Resources </div>
        <%= link_to create_nft_path do %>
          <div class="text-white px-4 font-bold text-[#c8cacd] hover:text-white cursor-pointer"> Create </div>
        <% end %>
        <%= link_to profile_path,id: "profile" do %>
          <div class="text-white px-4 font-bold text-[#c8cacd] hover:text-white cursor-pointer"> Profile </div>
        <% end %>
        <button type="button" id="btnConnect" class="text-white px-4 font-bold text-[#c8cacd] hover:text-white cursor-pointer text-[30px]">
            <%= fa_icon('wallet',type: :solid, class: "fd") %>
        </button>
        <button id="btnLogout" class="text-white px-4 font-bold text-[#c8cacd] hover:text-white cursor-pointer"> Logout </button>
        <div class="text-[#8a939b] text-3xl font-black px-4 hover:text-white cursor-pointer">
         
        </div>
      </div>
    </div>

app/views/homes/create_nft.html.erb
<div class="min-h-full flex">
  <div class="bg-white shadow-2xl rounded-xl mt-8 mx-auto flex-1 flex flex-col justify-center py-12 px-4 sm:px-6 lg:flex-none lg:px-20 xl:px-24">
    <div class="mx-auto w-full max-w-sm lg:w-96">
      <div>
        <h2 class="mt-6 text-3xl font-extrabold text-gray-900">
            Create New Item
        </h2>
       
      </div>
      <div class="mt-8">       
        <div class="mt-6">
            <%= render "homes/form" %>
        </div>
    </div>    
</div>
<%= javascript_pack_tag "nft_ui" %>

app/views/homes/edit_nft.html.erb
<div class="min-h-full flex">
  <div class="bg-white shadow-2xl rounded-xl mt-8 mx-auto flex-1 flex flex-col justify-center py-12 px-4 sm:px-6 lg:flex-none lg:px-20 xl:px-24">
    <div class="mx-auto w-full max-w-sm lg:w-96">
      <div>
        <h2 class="mt-6 text-3xl font-extrabold text-gray-900">
            Edit Item
        </h2>
       
      </div>
      <div class="mt-8">       
        <div class="mt-6">
            <%= render "homes/form" %>
        </div>
    </div>    
</div>
<%= javascript_pack_tag "nft_ui" %>
<script>
  const param = new URLSearchParams(window.location.search);
  let tokenAddress = param.get("tokenAddress");
  let tokenId = param.get("tokenId");
  editNft(tokenAddress,tokenId);
  itemDetail(tokenAddress, tokenId);
</script>

app/views/homes/homepage.html.erb
<div class="w-full">
    <div class="relative">
      <div class="before:content-[''] before:bg-red-500 bg-black before:absolute before:top-0 before:left-0 before:right-0 before:bottom-0 before:bg-[url('https://lh3.googleusercontent.com/ujepnqpnL0nDQIHsWxlCXzyw4pf01yjz1Jmb4kAQHumJAPrSEj0-e3ABMZlZ1HEpJoqwOcY_kgnuJGzfXbd2Tijri66GXUtfN2MXQA=s250')] before:bg-cover before:bg-center before:opacity-30 before:blur">
        <div class="flex h-screen relative justify-center flex-wrap items-center">
          <div class="w-6/12">
            <div class="relative text-white text-[46px] font-semibold">
              Discover, collect, and sell extraordinary NFTs
            </div>
            <div class="text-[#8a939b] container-[400px] text-2xl mt-[0.8rem] mb-[2.5rem]">
              CsSoft is the world&apos;s first and largest NFT marketplace
            </div>
            <div class="flex">
              <button class="relative text-lg font-semibold px-12 py-4 bg-[#2181e2] rounded-lg mr-5 text-white hover:bg-[#42a0ff] cursor-pointer">Explore</button>
              <%= link_to "Create",create_nft_path, class: "relative text-lg font-semibold px-12 py-4 bg-[#363840] rounded-lg mr-5 text-[#e4e8ea] hover:bg-[#4c505c] cursor-pointer" %>
            </div>
          </div>
          <div class="rounded-[3rem]">
            <img
              className="rounded-t-lg"
              src="https://lh3.googleusercontent.com/ujepnqpnL0nDQIHsWxlCXzyw4pf01yjz1Jmb4kAQHumJAPrSEj0-e3ABMZlZ1HEpJoqwOcY_kgnuJGzfXbd2Tijri66GXUtfN2MXQA=s550"
              alt=""
            />
            <div class="h-20 bg-[#313338] p-4 rounded-b-lg flex items-center text-white">
              <img
                className="h-[2.25rem] rounded-full"
                src="https://lh3.googleusercontent.com/qQj55gGIWmT1EnMmGQBNUpIaj0qTyg4YZSQ2ymJVvwr_mXXjuFiHJG9d3MRgj5DVgyLa69u8Tq9ijSm_stsph8YmIJlJQ1e7n6xj=s64"
                alt=""
              />
              <div class="flex flex-col justify-center ml-4">
                <div className={style.name}>Jolly</div>
                <a
                  className="text-[#1868b7]"
                  href="https://CsSoft.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/2324922113504035910649522729980423429926362207300810036887725141691069366277"
                >
                  hola-kanola
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  
</div>

<div className="overflow-hidden"> 
    <div class="mt-[45px] ml-[50px] text-white font-[600] text-[30px]">For Sale </div>
    <div id="item-for-sale" class="flex flex-wrap ">    
    </div>
</div>

<%= javascript_pack_tag "nft_ui" %>
<script>
  getItemsForSale();
</script>

app/views/homes/nft_collection.html.erb
<div className="overflow-hidden"> 
    <div id="content" class="flex flex-wrap ">    
    </div>
</div>
<%= javascript_pack_tag "nft_ui" %>
<script>
   saveNftsToDb () ; 
</script>

app/views/homes/nft_detail.html.erb
<div>
    <div class="w-full bg-[#303339] p-2" id="only-onwner-tab">
            <div class="mx-auto max-w-[1280px] min-w-[1024px] bg-[#303339] flex justify-end">
            <a class="float-right px-14 py-4 text-white bg-sky-600 rounded-xl mr-2" id="edit-button">Edit</a>
            <button class="float-right px-14 text-white py-4 bg-sky-600 rounded-xl" id="sell-button">Sell</button>
            </div>
    </div>
    <div class = "mx-auto max-w-[1280px] min-w-[1024px] flex flex-col items-center container-lg text-[#e5e8eb]">
        <div class = "container p-6">
            <div class = "flex">
            <div class = "flex-[1.4] mr-4">
                <!-- Nft image -->
                <div class="border border-[#E5E8EB] rounded-xl ">
                    <div class = "p-2 rounded-t-lg">
                        <div class = "flex items-center">
                        <IoMdSnow />
                        <div class = "flex-1 flex items-center justify-end">
                            <AiOutlineHeart />
                            2.3K
                        </div>
                        </div>
                    </div>
                    <div class="">
                        <img class="mx-auto" id="item-image" />
                    </div>
                </div>
                <!-- Description -->
                <div class="mt-8 border border-[#E5E8EB] rounded-xl ">
                    <div class = "p-2 rounded-xl border-[#151c22] border">
                        <div class = "flex items-center">
                        <IoMdSnow />
                        <div class = "p-4 flex-1 flex items-center justify-end">
                            Description
                        </div>
                        </div>
                    </div>
                    <div class="p-8 bg-[#353840] rounded-b-xl border-[#151c22] border ">
                        <span id="description"></span>
                    </div>
                </div>
                <!-- About this item -->
                <div class="mt-8 border border-[#E5E8EB] rounded-xl ">
                    <div class = "p-2 rounded-t-lg border-[#151c22] border">
                        <div class = "flex items-center">
                        <IoMdSnow />
                        <div class = "p-4 flex-1 flex items-center justify-end">
                            About this item
                        </div>
                        </div>
                    </div>
                    <div class="p-[15px] rounded-b-xl  bg-[#353840] ">
                        <div class="flex">
                            <div class="flex-[1.8]">Contract Address</div>
                            <div id="item-contract" class=""></div>
                        </div>
                        <div class="flex">
                            <div class="flex-[1.8]">Token Id</div>
                            <div id="item-tokenid" class=""></div>
                        </div>
                        <div class="flex">
                            <div class="flex-[1.8]">Token Standard</div>
                            <div id="item-token-standard" class=""></div>
                        </div>
                        <div class="flex">
                            <div class="flex-[1.8]">Blockchain</div>
                            <div id="item-chain" class=""></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class = "flex-[2] ml-4">
                <GeneralDetails selectedNft={selectedNft} />
                <button class="float-right px-4 py-4 bg-sky-600 rounded-xl" id="refresh-metadata-button">Refresh MetaData</button>
                <div class = "flex">
                    <div class = "h-36 flex flex-col flex-1 justify-between mb-6">
                        <div class = "text-[#2081e2]">Bored Ape Yacht Club</div>
                        <div id="name" class = "text-3xl font-extrabold"></div>
                        <div class = "flex">
                        <div class = "text-[#8a939b] mr-4">
                            Owned by <span id="owner" class = "text-[#2081e2]"></span>
                        </div>
                        <div class = "flex items-center text-[#8a939b]">
                            <AiFillHeart class = "mr-1" /> 2.3K favorites
                        </div>
                        </div>
                    </div>
                </div>

                <Purchase
                <div class="flex h-20 w-full items-center rounded-lg border border-[#151c22] bg-[#303339] px-12">
                    <Toaster position="bottom-left" reverseOrder={false} />
                    <!-- isListed === 'true' ? (
                        <>
                        <div
                            onClick={() => {
                            enableButton ? buyItem(selectedMarketNft.id, 1) : null
                            }}
                            class= "mr-8 flex items-center py-2 px-12 rounded-lg cursor-pointer bg-[#2081e2] hover:bg-[#42a0ff]"
                        >
                            <IoMdWallet class = "text-xl" />
                            <div class = "text-xl" >Buy Now</div>
                        </div>
                        <div
                            class= "mr-8 flex items-center py-2 px-12 rounded-lg cursor-pointer bg-[#2081e2] hover:bg-[#42a0ff]"}
                        >
                            <HiTag class = "text-xl" />
                            <div class = "text-xl" >Make Offer</div>
                        </div>
                        </>
                    ) : (
                        <div class= "mr-8 flex items-center py-2 px-12 rounded-lg cursor-pointer bg-[#2081e2] hover:bg-[#42a0ff]">
                        <IoMdWallet class = "text-xl" />
                        <div class = "ml-2 text-lg font-semibold">List Item</div>
                        </div>
                    -->
                </div>
            </div>
            </div>
            <ItemActivity />
        </div>
    </div>
</div>
<%= javascript_pack_tag "nft_ui" %>
<script>
    const params = new URLSearchParams(window.location.search);
    let tokenAddress = params.get("tokenAddress");
    let tokenId = params.get("tokenId");
    itemDetail(tokenAddress, tokenId);
</script>

app/views/homes/profile.html.erb
<div class="min-h-full flex">
  <div class="bg-white shadow-2xl rounded-xl mt-8 mx-auto flex-1 flex flex-col justify-center py-12 px-4 sm:px-6 lg:flex-none lg:px-20 xl:px-24">
    <div class="mx-auto w-full max-w-sm lg:w-96">
      <div>
        <h2 class="mt-6 text-3xl font-extrabold text-gray-900">
            Profile Settings
        </h2>
       
      </div>
      <div class="mt-8">       
        <div class="mt-6">
            <%= form_tag do %>
                <img id="user-avatar" class="mt-2 user-avatar h-[150px] w-[150px] mx-auto rounded-full"> 
                <div id="edit-user-avatar" class="edit-icon hidden user-avatar  mt-[-150px] ml-[117px] absolute h-[150px] bg-black opacity-[0.5] w-[150px] mx-auto rounded-full">
                    <i class="fa fa-edit mt-[65px] ml-[68px]" style="color:white; font-size:24px"></i>
                </div>
                <%= file_field_tag :avatar, class:"avatar h-0 w-0 opacity-0",onchange: "updateProfile()" %>                
                
                <%= label_tag :username, "Name", class:"text-[20px] font-bold block text-sm text-gray-700"  %>
                    <%= text_field_tag :username,"",id: "username",placeholder: "Enter your name", class:" mt-4 appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-sky-500 focus:border-sky-500 sm:text-sm" %>
                </div>
                <div class="space-y-1">
                    <%= label_tag :email,"Email Address",  class:"mt-8 text-[20px] font-bold block text-sm text-gray-700"  %>
                    <%= email_field_tag :email,"",id: "email", placeholder: "Enter your email", class:"mt-4 appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-sky-500 focus:border-sky-500 sm:text-sm" %>
                </div>
                <div class="space-y-1 mt-2">
                    <button type="button" onclick="updateProfile()" id="update-profile-button" class="w-full mt-8 flex justify-center py-4 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
                        Update Profile
                    </button>
                </div>     
            <% end %>   
        </div>
    </div>    
</div>
<%= javascript_pack_tag "nft_ui" %>
<script>
openUserInfo();

$(".user-avatar").hover(function(){
    $(".edit-icon").removeClass("hidden");
},
function(){
    $(".edit-icon").addClass("hidden");
})

$("#edit-user-avatar").on("click",function () {
    $(".avatar").click();
})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NftTimestamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/web3/1.7.1/web3.min.js" integrity="sha512-GKw4QT/RccGJIwQxY3MhyiQ5pHrhQ8SuKFEafV+WcpOvtz7iYFQuQGFCvmGlHLctJTe8KrWU1FqvF7VOkEAJtw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-[#121212]">
    <div class="w-full">
      <%= render "homes/header" %>
      <%= yield %>
    </div>
  </body>
</html>
<%=javascript_pack_tag 'market_place'%>